server:
  port: 8083

spring:
   mongodb:
      uri: mongodb://localhost:27017/fitnessrecommendations
      database: fitnessrecommendations
    
   rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest



eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/


rabbitmq:
  exchange:
    name: fitness-exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking


groq:
  api:
    url: "https://api.groq.com/openai/v1/chat/completions"
    key: "${GROQ_API_KEY:YOUR_GROQ_API_KEY_HERE}"
    model: "llama3-8b-8192"