server:
  port: 8083

spring:
   mongodb:
      uri: mongodb://localhost:27017/fitnessrecommendations
      database: fitnessrecommendations
    
   rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest



eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/


rabbitmq:
  exchange:
    name: fitness-exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking


huggingface:
  api:
    url: "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2"
    key: "${HUGGINGFACE_API_KEY:YOUR_HUGGINGFACE_TOKEN_HERE}"